# Permalinks
permalink:           pretty

# Setup
title:               LengaLenga
tagline:             Teste ao Jekyll
url:                 http://lengalen.ga
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Bruno Sousa
  url:               https://twitter.com/brcsousa
  email:             brcsousa@gmail.com

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
